name: Dependency Review

on:
  pull_request:
    branches: [main, develop]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    name: Dependency Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Analyze dependencies
      uses: actions/dependency-review-action@v4
      with:
        fail-on-severity: high
        comment-summary-in-pr: always